### ISSUE TITLE
Change font types to remain consistent

### ISSUE THREAD

**Issue by smarziano** [smartchicago/cutgroup#28]
We want to stay consistent with the CUTGroup brand, and therefore, would like to use the same font types and colors used for The CUTGroup book: http://www.cutgroupbook.org/

Title font: Raleway
Text font: Noto Serif

**Comment by shua123** [comment]
Fonts are updated on Staging site.

**Comment by danxoneil** [comment]
Looking good for now-- need to engage a designer to tighten this up.

**Comment by smarziano** [comment]
Fonts have been updated and while a designer might be engaged in the future, this task is completed and the website is more consistent with CUTGroup brand.
