### ISSUE TITLE
Replace city map with county/ city map

### ISSUE THREAD

**Issue by danxoneil** [smartchicago/cutgroup#29]
For launch, here's how we'll handle the map image:

-- Remove existing city image (keep in mind: these signup counts are inaccurate in two ways a/ ward 1 has become a default for people who bail on accurate ward, and b/ there are maybe some issues with the incrementer function, related to Patterns or some other muff up in the signup process
-- Replace with a view of entire Cook County with static, up-to-date signup counts for city wards and outlines for county municipialities. This will not be updated automatically and will immediately be inaccurate, but will be solved in a couple weeks in issue #30

**Comment by shua123** [comment]
New map of city wards and suburban municipalties & townships is up on staging.

**Comment by smarziano** [comment]
This is completed. More work needs to be done in terms of the map being automatically updated, but that relates to backend work and geocoding tester addresses.
