### ISSUE TITLE
Update contact information

### ISSUE THREAD

**Issue by smarziano** [smartchicago/cutgroup#37]
We need to update this contact information on the CUTGroup homepage (http://www.cutgroup.org/):
"Questions, comments, concerns? Hit us here: Daniel X. O'Neil, doneil@cct.org or (773) 960-6045."

Change to "Questions, comments, concerns? Please write Sonja Marziano, Project Coordinator of the Smart Chicago Collaborative, at smarziano@cct.org."

Also on the "Thank you" page: 
"If you have any questions, please write Dan O'Neil of the Smart Chicago Collaborative at doneil@cct.org"
Please switch to "please write Sonja Marziano of the Smart Chicago Collaborative at smarziano@cct.org"

**Comment by shua123** [comment]
Contact info updated with https://github.com/smartchicago/cutgroup/commit/0cdba28f67426185ee459d1396a52272ba31b60f
